
services:
  app:
    build: .
    container_name: go_app
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=mydb
    depends_on:
      - db
    networks:
      - app-network
    restart: always  

  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  beanstalkd:
    container_name: ddev-beanstalkd
    image: schickling/beanstalkd
    restart: "no"
    expose:
      - 11300 # beanstalkd доступен через этот порт внутри контейнера (порт по умолчанию для beanstalkd)
    ports:
      - 11300:11300
    labels:
      com.ddev.site-name: "sitename"
    volumes:
      - ".:/mnt/ddev_config"
    networks:
    - app-network


volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge